package org.abapps.app.resource.strings

interface IStringResources {
    val invoice: String
    val transfer: String
    val settings: String
    val exit: String
    val retry: String
    val warning: String
    val doYouWantToCloseApp: String
    val error: String
    val enterYourInfo: String
    val userName: String
    val password: String
    val ok: String
    val no: String
    val yes: String
    val cancel: String
    val tryAgain: String
    val somethingWrongHappened: String
    val noInternetMessage: String
    val noInternetDescription: String
    val nullDataMessage: String
    val nullDataDescription: String
    val userNotFound: String
    val enterYourPasscode: String
    val logo: String
    val logonError: String
    val invoiceNumber: String
    val invoiceType: String
    val status: String
    val regular: String
    val returnInvoice: String
    val customer: String
    val sourceType: String
    val store: String
    val cashier: String
    val salesPerson: String
    val comment: String
    val brandon: String
    val items: String
    val allItems: String
    val addItem: String
}