package org.abapps.app.presentation.screens.posInvoiceScreen

interface InvoiceInteractions {
    fun onClickAddItem()
    fun onClickDone()
    fun onClickBack()
    fun onClickItemFromAllItems(index: Int)
    fun onClickItemFromInvoice(index: Int)
    fun onClickExpandedCard(expandedCardStatus: ExpandedCardStatus)
    fun onClickItemDelete(itemId: Long)
    fun showErrorScreen()
    fun onChooseCustomer(id: Long)
    fun onChooseStore(id: Long)
    fun onChooseSalesPerson(id: Long)
    fun onChooseInvoiceType(id: Long)
    fun onCommentChanged(comment: String)
    fun onChangeQty(qty: String, itemId: Long)
    fun onChangeDiscount(discountAmount: String)
    fun onDismissErrorDialogue()
    fun onChooseDiscount(id: Long)
    fun onClickItemDiscount(itemId: Long)
    fun onDismissSettingsDialogue()
    fun onClickOkInDiscountDialog()
    fun onChangeDiscountItem(discountAmount: String)
    fun onChooseDiscountItem(id: Long)
    fun onAddScanQR()
    fun onBarcodeDetected(barcode: String)
}