package org.abapps.app.resource.strings.arabic

import org.abapps.app.resource.strings.IStringResources

data class Arabic(
    override val invoice: String = "فاتورة",
    override val transfer: String = "نقل",
    override val settings: String = "الاعدادات",
    override val exit: String = "الخروج",
    override val userName: String = "اسم المستخدم",
    override val password: String = "كلمة المرور",
    override val ok: String = "تم",
    override val cancel: String = "الغاء",
    override val tryAgain: String = "حاول مجددا",
    override val somethingWrongHappened: String = "يبدو أن حصل خطأ ما الرجاء المحاولة مره اخري",
    override val noInternetMessage: String = "لا يوجد انترنت",
    override val noInternetDescription: String = "بالرجاء التأكد من الاتصال بالانترنت و حاول مره اخري",
    override val nullDataMessage: String = "لا يوجد",
    override val nullDataDescription: String = "لا يوجد بيانات قم باضافة بيانات ثم حاول مره اخري",
    override val enterYourInfo: String = "ادخل بياناتك",
    override val warning: String = "تحذير",
    override val error: String = "خطأ",
    override val userNotFound: String = "هذا المستخدم غير موجود",
    override val enterYourPasscode: String = "ادخل الرقم السري",
    override val retry: String = "اعادة المحاوله",
    override val doYouWantToCloseApp: String = "هل تريد اغلاق التطبيق ؟",
    override val no: String = "لا",
    override val yes: String = "نعم",
    override val logo: String = "شعار",
    override val logonError: String = "خطأ في التسجيل",
    override val invoiceNumber: String = "رقم الفاتورة",
    override val invoiceType: String = "نوع الفاتورة",
    override val status: String = "الحاله",
    override val regular: String = "عادي",
    override val returnInvoice: String = "ارجاع",
    override val customer: String = "العميل",
    override val sourceType: String = "نوع المصدر",
    override val store: String = "المحل",
    override val cashier: String = "الكاشير",
    override val salesPerson: String = "البائع",
    override val comment: String = "تعليق",
    override val brandon: String = "برانداون",
    override val items: String = "الأصناف",
    override val allItems: String = "جميع الأصناف",
    override val addItem: String = "اضافة صنف",
    override val subTotal: String = "اجمالي سعر الصنف",
    override val totalTax: String = "اجمالي الضريبه",
    override val netTotal: String = "اجمالي السعر بعد الضريبه",
    override val fee: String = "مصاريف",
    override val amount: String = "المبلغ",
    override val totalPaid: String = "اجمالي المدفوع",
    override val remaining: String = "المتبقي",
    override val taken: String = "المدفوع",
    override val given: String = "المتبقي", override val discount: String = "خصم",
) : IStringResources