package org.abapps.app.domain.entities

data class Customer(
    val id: Int,
    val code: String,
    val firstName: String,
    val lastName: String,
    val fullName: String,
    val scomId: Int,
    val storeId: Int,
    val className: String,
    val storeName: String,
    val priceLevel: Int,
    val discId: Int,
    val customerClassId: Int,
    val active: Boolean,
    val reasonDeActive: String,
    val phone: String,
    val phone2: String,
    val phone3: String,
    val address: String,
    val address2: String,
    val email: String,
    val socialId: String,
    val ar: Boolean,
    val creditLimit: Float,
    val createDate: String,
    val modifiedDate: String,
    val userID: Int,
    val eType: String,
    val eIdNumber: String,
    val totalInvoices: Float,
    val returnedInvoices: Int,
    val invoicesCount: Int,
    val countReturned: Int,
)