package org.abapps.app.domain.entities

data class Item(
    val itemID: Long = 10000003869,
    val itemCode: Int = 3465,
    val upc: Int = 654,
    val alu: Int = 654,
    val name: String = "طقم ملايه بولي قطن",
    val name2: String = "uhukhkjhk",
    val description: String = " خسعيابستي بمتس بهتسي بمتسيمنب تسيمن بتمينتب منسيت بمنيست بمنتسيم بنتيسمن تبمن",
    val styleId: Int = 0,
    val styleName: String = "احمر",
    val onHand: Int = 51,
    val freeCard: Boolean = true,
    val freeCardPrice: Int = 10,
    val price: Int = 1000,
    val taxPerc: Int = 14,

    val qty: Int = 1,
    val itemDiscount: Int = 1,

    val grid1: String = "",
    val grid2: String = "",
    val grid3: String = "",
    val vendId: Int = 231654,
    val vendName: String = "",
    val nonInvn: Boolean = false,
    val taxable: Boolean = true,
    val taxId: Int = 151321,
    val itemType: String = "",
    val sClassId: Int = 151321,
    val subClass: String = "",
    val classId: Int = 151321,
    val className: String = "",
    val deptId: Int = 151321,
    val department: String = "",
    val active: Boolean = true,
    val openPrice: Boolean = false,
    val UDF1: String = "",
    val UDF2: String = "",
    val UDF3: String = "",
    val UDF4: String = "",
    val UDF5: String = "",
    val UDF6: String = "",
    val UDF7: String = "",
    val UDF8: String = "",
    val UDF9: String = "",
    val UDF10: String = "",
    val UDF11: String = "",
    val UDF12: String = "",
    val UDF13: String = "",
    val UDF14: String = "",
    val UDF15: String = "",
    val UDF16: String = "",
    val UDF17: String = "",
    val UDF18: String = "",
    val UDF19: String = "",
    val UDF20: String = "",
    val indexId: Int = 151321,
)
